//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVKH
    {
        public string ID { get; set; }
        public string MADK { get; set; }
        public string MADV { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHONGTHUE PHONGTHUE { get; set; }
    }
}
