//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MAHD { get; set; }
        public string TENHD { get; set; }
        public Nullable<int> MADV { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
