//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string MADK { get; set; }
    
        public virtual PHONGTHUE PHONGTHUE { get; set; }
    }
}
