//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string CMND_NV { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> roleID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual Ref_Role Ref_Role { get; set; }
    }
}
