//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGTHUE
    {
        public int MADK { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> SOPHONG { get; set; }
        public Nullable<System.DateTime> NGAYDEN { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
